FROM ghcr.io/dockhippie/nginx:latest-arm64@sha256:e106bf44bfc6729e31f55d8e3afc56b9e7fb1aa3a4de94798a81d5f726f8ceb0

VOLUME ["/etc/php8/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php8@testing php8-fpm@testing php8-ctype@testing php8-curl@testing php8-dom@testing php8-gd@testing php8-iconv@testing php8-intl@testing php8-json@testing php8-mysqli@testing php8-mysqlnd@testing php8-openssl@testing php8-opcache@testing php8-pdo@testing php8-pdo_mysql@testing php8-pdo_pgsql@testing php8-pdo_sqlite@testing php8-pear@testing php8-pgsql@testing php8-phar@testing php8-sqlite3@testing php8-xml@testing php8-zip@testing php8-mbstring@testing php8-simplexml@testing php8-tokenizer@testing php8-xmlwriter@testing php8-fileinfo@testing php8-soap@testing php8-apcu@testing php8-pecl-redis@testing php8-pecl-memcached@testing git && \
  ln -sf /usr/bin/php8 /usr/bin/php && \
  rm -rf /var/cache/apk/* /etc/php8/* && \
  mv /srv/www/index.html /srv/www/index.php

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php8/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
