FROM webhippie/nginx:latest-arm64@sha256:19df21c136b421597c55c3857efa3d5325044a4145c2a5572864c730999ead2f

VOLUME ["/etc/php7/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php7 php7-fpm php7-ctype php7-curl php7-dom php7-gd php7-iconv php7-intl php7-json php7-mysqli php7-mysqlnd php7-openssl php7-opcache php7-pdo php7-pdo_mysql php7-pdo_pgsql php7-pdo_sqlite php7-pear php7-pgsql php7-phar php7-sqlite3 php7-xml php7-zip php7-mbstring php7-simplexml php7-tokenizer php7-xmlwriter php7-fileinfo php7-soap php7-apcu php7-redis php7-pecl-memcached git && \
  ln -sf /usr/bin/php7 /usr/bin/php && \
  rm -rf /var/cache/apk/* /etc/php7/* && \
  mv /srv/www/index.html /srv/www/index.php

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php7/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
