FROM webhippie/nginx:latest-arm64@sha256:38a559c0232cf3b1df332d56a95f054b2c5f7acb484ffa00b1176ba34d34faf3

VOLUME ["/etc/php7/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php7@testing php7-fpm@testing php7-ctype@testing php7-curl@testing php7-dom@testing php7-gd@testing php7-iconv@testing php7-intl@testing php7-json@testing php7-mysqli@testing php7-mysqlnd@testing php7-openssl@testing php7-opcache@testing php7-pdo@testing php7-pdo_mysql@testing php7-pdo_pgsql@testing php7-pdo_sqlite@testing php7-pear@testing php7-pgsql@testing php7-phar@testing php7-sqlite3@testing php7-xml@testing php7-zip@testing php7-mbstring@testing php7-simplexml@testing php7-tokenizer@testing php7-xmlwriter@testing php7-fileinfo@testing php7-soap@testing php7-pecl-apcu@testing php7-pecl-redis@testing php7-pecl-memcached@testing git && \
  ln -sf /usr/bin/php7 /usr/bin/php && \
  rm -rf /var/cache/apk/* /etc/php7/* && \
  mv /srv/www/index.html /srv/www/index.php

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php7/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
