FROM webhippie/nginx:latest-arm64@sha256:9ccf2ac49840e579ab2a7b37db4de1dac2b40df2f00fed2da82226a6f489790a

VOLUME ["/etc/php8/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php8 php8-fpm php8-ctype php8-curl php8-dom php8-gd php8-iconv php8-intl php8-json php8-mysqli php8-mysqlnd php8-openssl php8-opcache php8-pdo php8-pdo_mysql php8-pdo_pgsql php8-pdo_sqlite php8-pear php8-pgsql php8-phar php8-sqlite3 php8-xml php8-zip php8-mbstring php8-simplexml php8-tokenizer php8-xmlwriter php8-fileinfo php8-soap php8-apcu php8-pecl-redis php8-pecl-memcached git && \
  ln -sf /usr/bin/php8 /usr/bin/php && \
  rm -rf /var/cache/apk/* /etc/php8/* && \
  mv /srv/www/index.html /srv/www/index.php

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php8/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
